version: '3.8'
services:
  expense-tracker:
    image: dev/expense-tracker:latest
    container_name: expense-tracker
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGO_URI=mongodb://mongodb:27017/expensetracker
    ports:
      - 25000:5000
    volumes:
      - /app/node_modules
      - /app/client/build
    restart: unless-stopped
