apiVersion: v1
kind: Service
metadata:
  name: webservice
  labels:
    name: webservice
    component: backend
  namespace: development
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    name: webservice
    component: backend
