apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  labels:
    name: webappservice
    component: frontend
  namespace: development
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http-port
      protocol: TCP
  #   nodePort: 31000
  selector:
    name: webappservice
    component: frontend
