apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  labels:
    name: mongo
    component: backend
  namespace: development
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: mongo
    component: backend
